// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:mindow/core/sync/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(OutboxRecordAdapter());
    registerAdapter(OutboxStateAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(OutboxRecordAdapter());
    registerAdapter(OutboxStateAdapter());
  }
}
