import 'package:hive_ce/hive.dart';
import 'package:mindow/core/sync/event_store.dart';

/// Declares the Hive `TypeAdapter`s generated by `hive_ce_generator`.
///
/// `firstTypeId: 10` reserves ids 0–9 for Hive internals / future core types,
/// matching `HiveRegistry.firstAvailableTypeId`. The spec order fixes the
/// assignment forever — DO NOT reorder or remove entries:
///   * `OutboxState`  → typeId 10
///   * `OutboxRecord` → typeId 11
///
/// The persisted assignment also lives in `hive_adapters.g.yaml` (committed).
/// Running `build_runner` generates `hive_adapters.g.dart` (the adapters) and
/// `hive_registrar.g.dart` (the `HiveRegistrar.registerAdapters()` extension).
@GenerateAdapters(
  [AdapterSpec<OutboxState>(), AdapterSpec<OutboxRecord>()],
  firstTypeId: 10,
)
part 'hive_adapters.g.dart';
